### ISSUE TITLE
Error when et too high

### ISSUE THREAD

**Issue by karma-riuk** [LP-RG/subxpat#91]
When running the following command:

```bash
python3.8 main.py input/ver/adder_i8_o5.v --template multilevel --encoding z3int --max-lv 6 --max-pit 6 -e 62
```

or 

```bash
 python3.8 main.py input/ver/adder_i6_o4.v --template multilevel --encoding z3int --max-lv 6 --max-pit 6 -e 5
```

I get the following output (and error):

```
Multilevel XPAT started...
path = 'output/report/grid_adder_i6_o4_6X6_et5_multilevel_xpat_asc_encz3int_modeNone_omaxNone_imaxNone_Multilevel_time20240910:103539.csv'
Only one iteration with et 5
benchmark adder_i6_o4
subgraph_extraction_time = 0.17644309997558594
subgraph exported at output/gv/subgraphs/adder_i6_o4_et5_modeNone_omaxNone.gv
Grid (6 X 6) and et=5 exploration started...
OpenSTA Warning! Design has 0 delay!
verifying all approximate circuits -> Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main()
  File "main.py", line 34, in main
    stats_obj = explore_grid(specs_obj)
  File "/home/karma/Documents/USI/Pozzi/SubXPAT/sxpat/xplore.py", line 195, in explore_grid
    candidate_data[4] = erroreval_verification_wce(specs_obj.exact_benchmark, candidate_name[:-2])
  File "/home/karma/Documents/USI/Pozzi/SubXPAT/sxpat/verification.py", line 27, in erroreval_verification_wce
    graph_obj_approx = Graph(approximate_benchmark)
  File "/home/karma/Documents/USI/Pozzi/SubXPAT/venv/lib/python3.8/site-packages/Z3Log/graph.py", line 45, in __init__
    self.clean_graph()
  File "/home/karma/Documents/USI/Pozzi/SubXPAT/venv/lib/python3.8/site-packages/Z3Log/graph.py", line 324, in clean_graph
    self.clean_wire_labels()
  File "/home/karma/Documents/USI/Pozzi/SubXPAT/venv/lib/python3.8/site-packages/Z3Log/graph.py", line 390, in clean_wire_labels
    if self.is_wire(n):
  File "/home/karma/Documents/USI/Pozzi/SubXPAT/venv/lib/python3.8/site-packages/Z3Log/graph.py", line 555, in is_wire
    if (not self.is_pi(node) and not self.is_po(node) and not self.is_gate(node) and
  File "/home/karma/Documents/USI/Pozzi/SubXPAT/venv/lib/python3.8/site-packages/Z3Log/graph.py", line 596, in is_gate
    if re.search('record', self.graph.nodes[node]['shape']):
KeyError: 'shape'
```

It seems like when the et is too high, the error occurs. With all et higher than the ones in the commands above, we have the same error every time.

**Comment by marco-biasion** [comment]
The problem has been fixed.
