### ISSUE TITLE
optimize-crash

### ISSUE THREAD

**Issue by MortezaRezaalipour** [LP-RG/subxpat#98]
When I run this command, it crashes after a while, and here's the log: 

`python3 main.py input/ver/adder_i12_o7.v  --subxpat --template=nonshared --parallel --min-labeling  --error-partitioning=asc --encoding=z3bvec --constants=optimize --wanted-models=1 --output-max=3 --input-max=6  --max-lpp=6 --max-ppo=6 --extraction-mode=55 -e=56`

```specs_obj = Specifications(
   exact_benchmark = adder_i12_o7,
   current_benchmark = adder_i12_o7,
   min_labeling = True,
   partial_labeling = False,
   extraction_mode = 55,
   imax = 6,
   omax = 3,
   min_subgraph_size = None,
   num_subgraphs = 1,
   max_sensitivity = None,
   subxpat = True,
   template = TemplateType.NON_SHARED,
   encoding = EncodingType.Z3_BITVECTOR,
   use_constants = False,
   constants_mode = ConstantsMode.OPTIMIZE,
   wanted_models = 1,
   max_lpp = 6,
   max_ppo = 6,
   max_pit = None,
   max_error = 56,
   error_partitioning = ErrorPartitioningType.ASCENDING,
   timeout = 10800,
   parallel = True,
   plot = False,
   clean = False,
)
SubXPAT started...
path = 'output/report/grid_adder_i12_o7_6X6_et56_subxpat_asc_encz3bvec_mode55_omax3_imax6_constoptimize_Sop1_time20241102:001958.csv'
persistance is:  0
iteration 1 with et 7, available error 56
benchmark adder_i12_o7
Labeling (explicit & parallel)... Done
labeling_time = 2.264226198196411
Partition with omax=3 and hard constraints, imax, omax, assumptions, and BitVec, DataType. Looking for largest partition
subgraph found -> SAT (#ofNodes=23)

...

subgraph_extraction_time = 0.24242806434631348
subgraph exported at output/gv/subgraphs/adder_i12_o7_Sop1_et42_encz3bvec_imax6_omax3_constoptimize_si11m0t503618640584734_i12m0t503649402927713_et49_mode55_omax3.gv
Grid (6 X 6) and et=49 exploration started...
Cell(0,1) at iteration 13 -> UNSAT
Cell(1,1) at iteration 13 -> UNSAT
Cell(2,1) at iteration 13 -> UNSAT
Cell(3,1) at iteration 13 -> UNSAT
Cell(4,1) at iteration 13 -> UNSAT
Cell(5,1) at iteration 13 -> UNSAT
Cell(6,1) at iteration 13 -> UNSAT
Cell(1,2) at iteration 13 -> UNSAT
verifying all approximate circuits -> Cell = (2, 2) iteration = 13 -> sat (1 models found)
ErrorEval PASS! with total wce = 48
Partition with omax=3 and hard constraints, imax, omax, assumptions, and BitVec, DataType. Looking for largest partition
subgraph found -> SAT (#ofNodes=8)
AAAAAAAAAAAAAAAAAAAAAAAA
False
AAAAAAAAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBb
-1
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBb
No gates are found in the graph! Skipping the subgraph extraction
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main()
  File "main.py", line 34, in main
    stats_obj = explore_grid(specs_obj)
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/xplore.py", line 253, in explore_grid
    verilog_filename, error_threshold = optimize_constants(specs_obj, best_data[4])
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/xplore.py", line 362, in optimize_constants
    results = manager.run()
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/template_manager/template_manager.py", line 112, in run
    self.generate_script()
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/template_manager/template_manager.py", line 81, in generate_script
    self._update_builder(builder)
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/template_manager/template_manager.py", line 456, in _update_builder
    super()._update_builder(builder)
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/template_manager/template_manager.py", line 340, in _update_builder
    builder.update(approximate_wires_declaration='\n'.join(
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/template_manager/template_manager.py", line 343, in <genexpr>
    if self._current_graph.is_subgraph_member(gate_name) else
  File "/home/morteza/SAT/c-optimize/SubXPAT_adder_i12/sxpat/annotatedGraph.py", line 2898, in is_subgraph_member
    if SUBGRAPH in self.subgraph.nodes[n]:
AttributeError: 'NoneType' object has no attribute 'nodes'

```

**Comment by marco-biasion** [comment]
The system changed drastically from when this problem was present, it should not reappear.
